#!/bin/bash

pacman -Sy
pacman --noconfirm --needed -S $MINGW_PACKAGE_PREFIX-{picotool,pico-sdk,arm-none-eabi-binutils,arm-none-eabi-gcc,arm-none-eabi-newlib,arm-none-eabi-gdb,cmake,ninja,gcc} git
git clone https://github.com/thewh1teagle/pico-setup
cd pico-setup
